version: '3.8'

services:
  testcraft:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
      - SESSION_SECRET=${SESSION_SECRET:-your-super-secret-session-key-change-this-in-production}
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - uploads:/app/uploads
    networks:
      - testcraft-network

volumes:
  uploads:

networks:
  testcraft-network:
    driver: bridge